version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: bubblow
      POSTGRES_PASSWORD: ewhain1886
      POSTGRES_DB: bubblow_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/__pycache__/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://bubblow:ewhain1886@db:5432/bubblow_db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  db_data:
